#------------------------------------------------#
#-CREADOR  : Real Strategy-----------------------#
#-CREADOR  : HACKING PCH-------------------------#
#-SCRIPT   : Generador-CCS-----------------------#
#-YOU-TUBE : HACKING PCH-------------------------#
#-FACEBOOK : @hackingpch-------------------------#
#-TELEGRAM : @hackingpch2------------------------#
#-LEMA     : NINGUN SISTEMA ES SEGURO------------#
#------------------------------------------------#















































































































































































































































































































































































































































































































































z="
";qBz=''\''"-u';yLz='z$bz';SCz=';xBz';gOz='z$gD';kGz=';pBz';cLz='z$UB';WJz='-g,'\''';lGz='='\''us';JNz='Cz$e';WHz=';jBz';DFz='in'\'';';BHz=' ◯'\'';';cNz='Cz$v';cOz='Dz$e';tLz='z$YB';LLz='z$EB';qHz='l ma';iPz='$JEz';wLz='z$KB';VBz='31m0';oDz=''\''nes';aIz=''\'';TC';RMz='$xBz';WOz='Dz$Z';qz='='\''Ca';HKz='B'\'';';LHz='  ☆┌';oJz='tho'\''';YIz='qz='\''';Rz='NEz=';PGz='='\''ra';nEz=' '\'';N';ePz='z$ME';YBz=';yDz';xNz='z$XB';AGz=' └'\'';';dCz=';REz';cEz='ones';pEz=''\'';SB';MBz='z='\''i';DOz='$SDz';iGz=''\'';OD';ZOz='Iz$b';aFz='='\''.\';tJz=''\''31m';dFz=''\''gy"';EMz='gz$m';fHz=';IDz';eFz=''\'';uC';MLz='z$FB';uCz='4'\'';c';oGz=''\'':  ';kLz='mz$K';iCz='a'\'';j';lCz='='\''GE';eKz='$Tz$';DMz='lBz$';XJz=';nBz';WGz='ate'\''';ZFz=';VBz';IGz='='\''s-';ZDz='='\''mp';FLz='$xz$';PBz='='\''xx';PPz='Ez$D';vOz='Dz$o';RKz='$Iz$';EDz=''\'';uB';gKz='$Hz$';QFz='='\''-q';fDz='c"'\'';';tMz='z$oB';BKz='WCz=';VIz='-h '\''';dGz='z='\''┘';tNz='Dz$N';UBz='Bz='\''';NLz='z$GB';PEz='▒'\'';w';ZPz='Ez$I';mBz=';RDz';WLz='Bz$O';aEz=''\''──┘';cz='Dz='\''';jBz='clea';sIz='m'\'';P';YFz='m+-'\''';bBz=' de ';pNz='Dz$J';jz='yt'\'';';MOz='Bz$s';Az='z="';Dz='┬─'\'';';vIz='d  '\''';NFz='P'\'';Y';qMz='z$SC';aPz='Ez$J';DKz='-'\'';U';wOz='Dz$p';Fz=''\''┘"'\''';yKz='$pz$';AFz='z='\''r';lEz=';Iz=';dOz='Dz$f';JIz='IBz=';hDz=''\''+ \';RJz='ZCz=';NMz='$tBz';BJz=''\''▒▒│';PDz=''\'';FE';eLz='z$WB';ELz='z$wz';iFz='RA'\'';';sJz='QBz=';LIz='"'\'';O';lHz='  GE';rIz=''\''[33';Gz=';FDz';TPz='z$oD';bEz='▒'\'';U';NPz='Ez$B';wHz='▒'\'';P';mHz=''\'';Bz';gFz=';cBz';QBz=' -'\'';';jHz=''\''te ';LOz='Jz$r';kOz='$jDz';IPz='wDz$';yGz='e'\'';Q';dHz='z='\''p';JCz=';uDz';OMz='$uBz';iMz='$PCz';NIz=''\'';MD';PHz='='\''ck';OIz='n u'\''';oMz='Bz$z';ZEz='ABz=';sLz='z$hB';yDz=' re'\''';KCz='='\''ME';UKz='$Mz$';HOz='gBz$';mCz='NE'\'';';oHz='on'\'';';JOz='Bz$T';jFz='CEz=';VOz='Dz$X';hHz=' l'\'';';MEz='as.'\''';aHz='-'\'';L';nHz='='\''ti';xLz='z$jB';Ez='FBz=';FJz=';GEz';hMz='$OCz';NEz=';Zz=';IBz=''\''│▒│';pMz='z$RC';mPz='$REz';pDz=' '\'';T';IIz='R '\'';';gIz='RBz=';fIz='c,'\'';';vCz='33mC';vKz='$lz$';KJz='='\''fu';bMz='$ICz';FBz=';OEz';GDz='cs-'\''';XGz=';kCz';ICz='='\''r'\''';BIz=''\''─┐ ';vBz='='\''ho';vJz='\e['\''';GEz='sCz=';uBz=';GCz';CNz='YCz$';VCz=''\''or-';CFz='='\'' b';EOz='$oBz';sMz='z$UC';GBz='='\''}'\''';hNz='Dz$B';ez=''\'';NC';RBz='PDz=';aCz=''\'';HB';MCz='jCz=';sOz='jBz$';KNz='Cz$f';jEz='z='\''3';dIz=';nCz';HNz='Iz$c';nBz='='\''mE';EGz=''\'';KC';hOz='z$dD';wKz='mz$n';XKz='$z$H';CHz='aCz=';YGz='='\'' a';YCz=';KEz';pFz=' de'\''';Hz='='\''ar';QPz='Ez$j';BMz='$YBz';cCz='┐▒▒'\''';xMz='iBz$';mOz='$lDz';APz='$sDz';FKz='MEz=';tKz='iz$j';CKz=''\''b, ';QNz='Cz$k';pHz='tz='\''';CPz='$uDz';xCz='-da'\''';aBz='"'\'';o';EHz='e'\'';J';eIz='='\''"-';cFz='nDz=';FGz='z='\''s';xEz=' .cc';rJz='ad'\'';';bCz='z='\''└';mKz='$Zz$';VEz='ner'\''';gBz='='\''RE';MJz='hz='\''';OBz=';XDz';CEz='lBz=';aLz='z$SB';lBz=' az'\''';FFz='sabl';JJz=''\'';Az';wNz='z$PB';yFz='='\''" ';gz='je '\''';GIz=';dBz';uJz='2'\'';J';kPz='$PEz';KDz='vali';MMz='$sBz';JHz='us'\'';';cGz='G'\'';l';DCz='='\''RA';bGz=''\''KIN';ADz='='\''ec';rCz='   '\''';OFz='▒│▒'\''';sBz='z='\''│';aNz='Cz$t';PMz='$vBz';sHz='z='\''x';eCz='='\'' p';aGz='pDz=';nFz=''\'';CD';pz=';gCz';IMz='$KBz';CJz='◯'\'';e';SIz='kz='\''';BDz='ha'\'';';AHz=';GBz';nOz='$mDz';XBz='-ca'\''';pIz=' C'\'';';fJz='-cc'\''';TLz='gz$L';EFz='rz='\''';tCz=''\''e[3';DGz='3mMe';uDz=';gz=';QDz='z='\''E';rz='nt'\'';';kMz='gz$Q';ENz='aCz$';SMz='$yBz';kBz=''\'';tC';cKz='Hz$I';OPz='Ez$C';mFz='mGen';ZCz='='\''2"';OJz=';XBz';MIz='de a';iKz='z$Vz';WNz='Cz$K';LBz=''\'';hC';RFz='L '\'';';CLz='$tz$';lIz='z='\''▒';jPz='$z$O';vFz='a'\'';K';ACz='"'\'';i';uNz='Dz$O';HLz='Bz$B';hIz=''\''6m.';eEz=';nz=';hEz='37mC';yIz='ne'\'';';oBz='je'\'';';FNz='bCz$';gGz='"'\'';N';iLz='ZBz$';GFz=''\'';PC';Vz='ar"'\''';XLz='Bz$Q';bPz='Ez$K';AIz=';Nz=';tIz=' \e[';xBz='gBz=';PNz='Cz$j';TFz=''\''OR ';kEz='456'\''';BOz='$QDz';cBz=''\'';lD';OEz=''\''|▒│';SKz='Jz$K';LJz='nc'\'';';TEz='='\''SI';rOz='hDz$';BNz='XCz$';nMz='Bz$Z';JBz=' '\'';A';BBz='36m-';IJz='echo';ZNz='Cz$s';fOz='Iz$J';sEz=';yBz';qJz='='\''er';EKz='/"'\'';';BEz='='\''m@';OCz='s'\'';Z';lOz='$kDz';JGz='va'\'';';ZMz='$GCz';hBz='AD'\'';';oKz='z$cz';oz='▒/"'\''';qIz='SCz=';QOz='Bz$w';iIz='\'\'';Q';VGz=''\'';mD';nNz='Dz$H';aJz='fDz=';WFz=''\'';QC';qEz='z='\''e';fPz='z$NE';TMz='$ACz';hz=';FCz';eDz='z='\''-';KOz='Dz$Y';fNz='Cz$y';vDz=''\''\e[';rDz=''\'';TB';AOz='$PDz';Nz='34m'\''';fLz='$Jz$';LKz='$Cz$';CBz=''\'';YD';Oz=';YBz';Yz='PT'\'';';yMz='VCz$';KHz='Mz='\''';Xz='='\''RI';UFz=' '\'';q';jLz='aBz$';GCz=''\''100';IKz='eval';vEz=''\''[36';JKz=' "$A';iz='='\''"p';yz=''\''m│▒';nIz=';eBz';XCz='ban'\''';TKz='z$Lz';uMz='z$pB';SOz='Bz$U';ZLz='z$RB';MGz=''\'';ED';KPz='yDz$';tFz='JCz=';XOz='Dz$a';ZHz='qBz=';mMz='Bz$Y';PLz='z$IB';YPz='GEz$';lLz='Bz$b';xJz=''\''o"'\''';xHz=''\'';bD';dKz='z$Qz';QGz=' c'\'';';GJz='M '\'';';UPz='z$pD';cHz=''\'';BC';KIz=''\''▒▒┌';vGz='PO'\'';';UDz='▒▒'\'';';VKz='Nz$O';vHz=''\''│▒/';fBz=';dDz';RHz=''\''ANA';MFz=''\''CRI';TBz='\'\'';W';Qz='--'\'';';lNz='Dz$F';GMz='Bz$o';qDz=' +--';dMz='$KCz';kCz=''\'';cz';cIz='pci'\''';BCz='tarj';TJz='t'\'';o';WCz='C'\'';C';jJz='eCz=';kKz='Xz$z';MPz='Dz$A';JPz='xDz$';OLz='z$HB';gLz='XBz$';INz='Cz$d';NJz='4m"'\''';ZGz=' g'\'';';HFz='z='\''y';dPz='z$LE';pOz='gDz$';ECz='DO'\'';';FHz='Ez='\''';XHz='='\''  ';dBz='z='\''l';GHz='gpch';ABz='┌'\'';V';JLz='z$CB';sGz='7mT'\''';oIz='='\''DE';oPz='$TEz';rNz='Dz$L';gPz='$HEz';Uz='Cz='\''';GNz='Pz$z';VMz='$CCz';yHz='+  '\''';RIz='nn'\'';';FIz='6mp'\''';WPz='EEz$';XNz='Bz$q';SNz='Cz$m';Lz='e'\'';L';TCz='='\''py';pLz='Bz$f';iEz=''\'';VD';BGz='fBz=';HJz='Hz='\''';pKz='$dz$';fKz='Uz$z';yBz=''\''1m+';gCz='kDz=';ZJz='do'\'';';OOz='Bz$u';Sz=''\''OOK';tz='"  ┌';LNz='Cz$g';eJz=''\'';oC';NBz='dad'\''';SGz=''\''Gua';Pz='='\''--';qGz='"+--';dz='T NA';nJz=''\'';sB';cMz='$JCz';GGz='.py'\''';kz='LDz=';UEz='ON'\'';';ODz='ener';sFz=' u'\'';';lFz='-'\'';v';IDz=''\''e a';qOz='dDz$';wDz='3'\'';p';mLz='Bz$c';sNz='Dz$M';eBz=' St'\''';cDz=' ─┐☆';oCz='[31m';YLz='Bz$g';NGz='-gu'\''';KMz='$iBz';sDz='z='\''m';VLz='Bz$N';JMz='$qBz';UOz='Dz$W';YKz='z$Iz';AJz='BBz=';nGz='iDz=';VFz=' PCH';rGz=''\'';EE';nPz='$SEz';QMz='$wBz';PCz=' -d ';MDz='='\''┐◯';WKz='z$Pz';nCz='bz='\''';UCz='xDz=';IHz='='\''l ';KBz='s al';MHz=''\'';iB';QEz='z='\''"';GKz=''\''ACE';fFz='-d,'\''';eOz='Dz$g';SEz=';OBz';HIz='='\''DO';HPz='vDz$';cPz='Ez$z';POz='Bz$v';jDz='▒│/'\''';mIz='▒▒┌'\''';wIz=';qCz';ONz='Bz$i';bNz='Iz$u';QJz='m+'\'';';oNz='Dz$I';bDz='Oz='\''';tOz='bz$i';BLz='z$sz';JFz=';UDz';Jz='KDz=';qKz='ez$f';YJz='='\''to';HCz=''\'';Gz';ANz='WCz$';uKz='z$kz';lMz='Cz$Y';BPz='$tDz';EEz=' '\'';Z';jOz='$iDz';qFz=';DCz';gNz='Cz$A';XIz='[O'\'';';nDz='CCz=';yEz=''\'';GD';WBz=''\'';dC';uLz='z$iB';MKz='Dz$z';RCz='aza'\''';bLz='z$TB';iDz='e'\'';T';nKz='az$b';VPz='z$qD';DHz=''\''o d';wz='DE '\''';oFz='"'\'';s';DLz='uz$v';iOz='z$hD';qLz='Bz$K';pJz=';wDz';oLz='Bz$e';hJz='='\''bi';PJz='='\''31';WDz='3'\'';f';xGz=''\''"+\';Zz='YCz=';uFz=''\''lid';wJz=';vz=';MNz='Cz$h';bz='o'\'';t';wFz='m\e'\''';yCz=';yCz';AEz=';HEz';IFz='uda'\''';PFz=';SEz';cJz=' '\'';D';CGz=''\''CS ';yNz='z$ZB';uHz=';Vz=';wMz='kBz$';uGz='='\''O ';bKz='z$z$';Cz='='\''/─';mNz='Dz$G';wBz='n2'\'';';vLz='Hz$z';aMz='$HCz';UIz=''\'';LC';RNz='Cz$l';wEz='m'\'';H';SJz=''\''rma';ULz='Bz$M';dJz='TUBE';HGz=';ICz';NDz='"'\'';l';UNz='Iz$n';PIz=';PEz';sCz=';xz=';pCz=''\'';pC';BFz=';bCz';lPz='$QEz';HHz=''\'';uz';pGz='\'\'';h';DPz='$jBz';jMz='$Pz$';FPz='iDz$';xKz='z$oz';RGz='HDz=';YMz='$FCz';Mz='z='\''[';HDz=';oz=';NCz=''\''eta';fEz=''\''No ';CIz=' '\'';M';vNz='Dz$v';EBz=' 50'\''';RDz='LEG'\''';VNz='Cz$p';wCz=''\'';vC';HMz='Bz$p';NKz='$Ez$';XMz='$ECz';tHz='xxx'\''';TIz='┐-┘─';hKz='Iz$Q';REz='  \'\''';AKz=' f'\'';';kNz='Dz$E';Iz='da'\'';';XEz='='\''so';TDz='='\''┐▒';aDz='lo'\'';';xFz=';CBz';LMz='$rBz';FCz='TEz=';LPz='Jz$g';lJz='d'\'';k';rBz=','\'';a';OHz=';IEz';EIz=''\'';rB';ZKz='$Qz$';jIz='er |';RPz='z$iD';az=''\''  F';mz=' '\'';S';bIz='z='\''O';rHz=''\'';WD';iNz='Dz$C';IOz='Qz$K';rMz='z$TC';aOz='Dz$P';sz='iz='\''';DEz=''\''  +';UGz='n2 .';jKz='$Wz$';jCz='e[32';dEz=''\'';KB';rFz='='\''de';YOz='Jz$X';UJz='mHAC';HEz=''\''cv ';DBz='z='\''u';gJz=';XCz';tBz=' \e'\''';hGz=' VER';Tz=' '\'';m';KGz='jz='\''';CMz='$ZBz';KKz='z$Bz';QCz=''\'';BD';xIz='='\''Ge';QIz='='\''ba';KFz='12'\'';';GOz='$gz$';hLz='YBz$';NNz='Cz$o';fz='z='\''a';bJz=''\''R  ';YNz='Cz$r';YEz=']"'\'';';kHz=' '\'';b';FOz='$pBz';eNz='Cz$x';uEz='UBz=';GPz='jDz$';LEz='z='\''d';kDz=';JDz';SDz=';DBz';QLz='z$Jz';FDz='z='\''c';tGz=';eDz';gDz='RCz=';WMz='$DCz';EJz=' DE'\''';mEz=''\'' -e';vMz='$gBz';XPz='FEz$';KLz='z$DB';YHz='\e'\'';';ALz='qz$r';TOz='Dz$V';kJz=''\''nti';dDz=''\'';aD';fMz='$MCz';CCz=''\'';dz';dNz='Cz$w';YDz=';SDz';aKz='Rz$S';VDz='QDz=';PKz='$Gz$';JEz='z='\''{';LGz='┴─┴─';JDz='g'\'';v';rLz='z$gB';jGz='hiv'\''';gEz='m'\'';g';eGz=';JBz';fCz='v '\'';';ZBz='='\''CS';jNz='Iz$D';SHz='L'\'';r';wGz='aBz=';KEz=''\'';wB';EPz='$bz$';DDz='[37m';LDz=''\'';Xz';xOz='Dz$q';FEz='+"'\'';';uIz=''\'';fC';OKz='z$Fz';dLz='z$VB';OGz=';rCz';GLz='yz$A';hFz='='\''NE';uOz='Dz$j';pBz='cCz=';yOz='$rDz';TGz='r'\'';t';WIz=';ACz';DNz='ZCz$';sKz='$hz$';CDz='mz='\''';UMz='$BCz';fGz='='\''1m';NOz='Bz$t';nz='z='\''/';AMz='$kBz';bHz='3mSC';TNz='Cz$z';eMz='$LCz';lDz='='\''as';kIz=''\'';EB';IEz='a'\'';E';VHz='7mF'\''';eHz='cio'\''';iJz='n '\'';';LFz='sDz=';Bz='";Wz';QKz='z$Hz';uz=''\'';BE';qNz='Dz$K';yJz=';xCz';ILz='Bz$P';gMz='$NCz';SFz='hDz=';SPz='z$jD';Kz=''\''arj';THz='37mS';FMz='Bz$n';lKz='z$Yz';gHz='='\''da';bOz='Dz$d';WEz=';ECz';SLz='KBz$';bFz='e['\'';';mDz=' t'\'';';SBz=''\'' + ';rEz='[31'\''';UHz=''\'';LE';lz=''\''tas';xz=';yz=';vz='z='\'' ';mGz='o '\'';';rKz='z$gz';hPz='$IEz';pPz='"';iHz='wCz=';XFz='z='\''1';LCz='  '\'';';RLz='$JBz';nLz='Bz$d';DIz='Mens';HBz=';Rz=';tDz='0\e'\''';XDz='CCS'\''';mJz='+---';oOz='$nDz';ZIz='spon';hCz=''\''mRe';xDz='z='\''o';COz='$RDz';qCz='z='\''v';NHz='-+"'\''';Wz=';MBz';QHz='AEz=';tEz='='\''b ';ROz='Bz$x';DJz='z='\''R';iBz='Fz='\''';VJz=''\'';DD';oEz='n ar';kFz=''\''YOU';
eval "$Az$z$Bz$Cz$Dz$Ez$Fz$Gz$Hz$Iz$Jz$Kz$Lz$Mz$Nz$Oz$Pz$Qz$Rz$Sz$Tz$Uz$Vz$Wz$Xz$Yz$Zz$az$bz$cz$dz$ez$fz$gz$hz$iz$jz$kz$lz$mz$nz$oz$pz$qz$rz$sz$tz$uz$vz$wz$xz$yz$ABz$Uz$BBz$CBz$DBz$EBz$FBz$GBz$HBz$IBz$JBz$cz$KBz$LBz$MBz$NBz$OBz$PBz$QBz$RBz$SBz$TBz$UBz$VBz$WBz$vz$XBz$YBz$ZBz$aBz$UBz$bBz$cBz$dBz$eBz$fBz$gBz$hBz$iBz$jBz$kBz$dBz$lBz$mBz$nBz$oBz$pBz$qBz$rBz$sBz$tBz$uBz$vBz$wBz$xBz$yBz$ACz$Uz$BCz$CCz$DCz$ECz$FCz$GCz$HCz$ICz$JCz$KCz$LCz$MCz$NCz$OCz$cz$PCz$QCz$vz$RCz$SCz$TCz$QBz$UCz$VCz$WCz$vz$XCz$YCz$ZCz$aCz$bCz$cCz$dCz$eCz$fCz$gCz$hCz$iCz$cz$jCz$kCz$lCz$mCz$nCz$oCz$pCz$qCz$rCz$sCz$tCz$uCz$cz$vCz$wCz$vz$xCz$yCz$ADz$BDz$CDz$DDz$EDz$FDz$GDz$HDz$IDz$JDz$UBz$KDz$LDz$MDz$NDz$Uz$ODz$PDz$QDz$RDz$SDz$TDz$UDz$VDz$tCz$WDz$vz$XDz$YDz$ZDz$aDz$bDz$cDz$dDz$eDz$fDz$gDz$hDz$iDz$sBz$jDz$kDz$lDz$mDz$nDz$oDz$pDz$cz$qDz$rDz$sDz$tDz$uDz$vDz$wDz$xDz$yDz$AEz$BEz$BDz$CEz$DEz$EEz$UBz$FEz$GEz$HEz$IEz$JEz$KEz$LEz$MEz$NEz$OEz$PEz$QEz$REz$SEz$TEz$UEz$cz$VEz$WEz$XEz$YEz$ZEz$aEz$bEz$Uz$cEz$dEz$vz$rCz$eEz$fEz$gEz$cz$hEz$iEz$jEz$kEz$lEz$mEz$nEz$cz$oEz$pEz$qEz$rEz$sEz$tEz$LCz$uEz$vEz$wEz$Uz$xEz$yEz$AFz$rCz$BFz$CFz$DFz$EFz$FFz$GFz$HFz$IFz$JFz$tEz$KFz$LFz$MFz$NFz$sBz$OFz$PFz$QFz$RFz$SFz$TFz$UFz$cz$VFz$WFz$XFz$YFz$ZFz$aFz$bFz$cFz$dFz$eFz$QEz$fFz$gFz$hFz$iFz$jFz$kFz$lFz$cz$mFz$nFz$AFz$oFz$qEz$pFz$qFz$rFz$sFz$tFz$uFz$vFz$XFz$wFz$xFz$yFz$AGz$BGz$CGz$Tz$UBz$DGz$EGz$FGz$GGz$HGz$IGz$JGz$KGz$LGz$MGz$vz$NGz$OGz$PGz$QGz$RGz$SGz$TGz$UBz$UGz$VGz$AFz$WGz$XGz$YGz$ZGz$aGz$bGz$cGz$dGz$tBz$eGz$fGz$gGz$UBz$hGz$iGz$FDz$jGz$kGz$lGz$mGz$nGz$oGz$pGz$UBz$qGz$rGz$jEz$sGz$tGz$uGz$vGz$wGz$xGz$yGz$QEz$rCz$AHz$yFz$BHz$CHz$DHz$EHz$FHz$GHz$HHz$IHz$JHz$KHz$LHz$MHz$eDz$NHz$OHz$PHz$DFz$QHz$RHz$SHz$cz$THz$UHz$jEz$VHz$WHz$XHz$YHz$ZHz$DEz$aHz$UBz$bHz$cHz$dHz$eHz$fHz$gHz$hHz$iHz$jHz$kHz$UBz$lHz$mHz$nHz$oHz$pHz$qHz$rHz$sHz$tHz$uHz$vHz$wHz$QEz$xHz$QEz$yHz$AIz$BIz$CIz$Uz$DIz$EIz$jEz$FIz$GIz$HIz$IIz$JIz$KIz$LIz$Uz$MIz$NIz$qEz$OIz$PIz$QIz$RIz$SIz$TIz$UIz$vz$VIz$WIz$XHz$XIz$YIz$ZIz$aIz$bIz$cIz$dIz$eIz$fIz$gIz$hIz$iIz$FHz$jIz$kIz$lIz$mIz$nIz$oIz$pIz$qIz$rIz$sIz$UBz$tIz$uIz$fz$vIz$wIz$xIz$yIz$AJz$BJz$CJz$DJz$EJz$FJz$DCz$GJz$HJz$IJz$JJz$KJz$LJz$MJz$NJz$OJz$PJz$QJz$RJz$SJz$TJz$cz$UJz$VJz$QEz$WJz$XJz$YJz$ZJz$aJz$bJz$cJz$FHz$dJz$eJz$vz$fJz$gJz$hJz$iJz$jJz$kJz$lJz$UBz$mJz$nJz$HFz$oJz$pJz$qJz$rJz$sJz$tJz$uJz$QEz$vJz$wJz$xJz$yJz$PGz$AKz$BKz$CKz$DKz$lIz$EKz$FKz$GKz$HKz$z$IKz$JKz$KKz$LKz$MKz$NKz$OKz$PKz$QKz$RKz$SKz$TKz$UKz$VKz$WKz$XKz$YKz$ZKz$aKz$bKz$cKz$dKz$eKz$fKz$gKz$hKz$iKz$jKz$kKz$gKz$hKz$lKz$mKz$nKz$oKz$pKz$qKz$rKz$sKz$QKz$RKz$tKz$uKz$vKz$wKz$xKz$yKz$ALz$BLz$CLz$DLz$bKz$cKz$ELz$FLz$GLz$HLz$ILz$bKz$cKz$JLz$KLz$LLz$MLz$bKz$cKz$NLz$OLz$PLz$bKz$cKz$QLz$RLz$XKz$YKz$ZKz$SLz$SLz$SLz$TLz$ULz$VLz$WLz$ILz$XLz$YLz$ZLz$aLz$bLz$cLz$dLz$eLz$WKz$XKz$YKz$fLz$gLz$hLz$hLz$hLz$hLz$hLz$hLz$hLz$iLz$QKz$RKz$jLz$kLz$lLz$mLz$nLz$oLz$pLz$qLz$YLz$rLz$bKz$cKz$sLz$tLz$tLz$tLz$tLz$tLz$tLz$uLz$bKz$vLz$gKz$hKz$wLz$wLz$wLz$wLz$wLz$wLz$wLz$xLz$yLz$AMz$BMz$BMz$BMz$CMz$XKz$YKz$ZKz$SLz$SLz$SLz$SLz$SLz$SLz$SLz$DMz$EMz$FMz$GMz$HMz$YLz$rLz$bKz$cKz$dKz$IMz$IMz$IMz$IMz$IMz$IMz$IMz$JMz$BMz$BMz$BMz$KMz$XKz$bKz$cKz$QLz$LMz$MMz$NMz$OMz$PMz$QMz$RMz$SMz$TMz$UMz$VMz$WMz$XMz$XKz$YKz$YMz$ZMz$aMz$bMz$cMz$dMz$eMz$IMz$fMz$gMz$hMz$iMz$jMz$QKz$XKz$YKz$ZKz$SLz$SLz$SLz$SLz$SLz$SLz$SLz$kMz$lMz$mMz$mMz$mMz$nMz$oMz$gKz$hKz$wLz$wLz$wLz$wLz$wLz$wLz$wLz$pMz$qMz$rMz$sMz$tMz$uMz$rKz$vMz$XKz$YKz$ZKz$SLz$SLz$SLz$SLz$SLz$SLz$SLz$wMz$hLz$hLz$hLz$xMz$QKz$XKz$YKz$fLz$yMz$ANz$BNz$SLz$CNz$DNz$ENz$FNz$GNz$gKz$HNz$INz$JNz$KNz$LNz$MNz$NNz$ONz$PNz$QNz$RNz$SNz$TNz$gKz$UNz$NNz$VNz$WNz$XNz$YNz$ZNz$aNz$SNz$TNz$gKz$bNz$cNz$dNz$WNz$XNz$eNz$fNz$gNz$hNz$iNz$MKz$gKz$jNz$kNz$lNz$mNz$nNz$oNz$pNz$qNz$rNz$sNz$tNz$uNz$vNz$bKz$vLz$gKz$hKz$wLz$wLz$wLz$wLz$wLz$wLz$wLz$wNz$xNz$tLz$tLz$tLz$tLz$yNz$bKz$cKz$dKz$IMz$IMz$IMz$IMz$IMz$IMz$IMz$AOz$BOz$COz$DOz$EOz$FOz$GOz$HOz$QKz$RKz$IOz$qLz$qLz$qLz$qLz$qLz$qLz$JOz$KOz$mMz$mMz$ONz$oMz$gKz$QKz$RKz$LOz$MOz$NOz$OOz$POz$QOz$ROz$SOz$TOz$UOz$UOz$VOz$KOz$WOz$XOz$MKz$gKz$QKz$RKz$YOz$mMz$mMz$mMz$mMz$nMz$oMz$gKz$ZOz$aOz$mLz$bOz$cOz$dOz$eOz$rLz$bKz$cKz$sLz$tLz$tLz$tLz$uLz$bKz$vLz$gKz$fOz$gOz$hOz$iOz$wLz$wLz$xLz$yLz$jOz$kOz$lOz$mOz$nOz$oOz$XKz$YKz$fLz$pOz$qOz$rOz$SLz$SLz$sOz$tOz$uOz$vOz$wOz$xOz$aOz$bKz$cKz$QLz$yOz$APz$BPz$CPz$IMz$DPz$EPz$FPz$GPz$HPz$IPz$JPz$KPz$QKz$RKz$LPz$MPz$NPz$OPz$PPz$QPz$lLz$RPz$SPz$TPz$UPz$VPz$WKz$XKz$YKz$fLz$WPz$XPz$YPz$SLz$SLz$sOz$tOz$uOz$nNz$ZPz$aPz$bPz$cPz$gKz$fOz$dPz$ePz$fPz$wLz$wLz$xLz$yLz$jOz$kOz$gPz$hPz$iPz$jMz$QKz$jPz$cPz$kPz$lPz$mPz$nPz$oPz$pPz"
